"""add unique constraint to books

Revision ID: 4a8aeaaa7448
Revises: d70621965e47
Create Date: 2026-05-26 18:36:36.158373

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4a8aeaaa7448"
down_revision: Union[str, Sequence[str], None] = "d70621965e47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_book_title_author", "books", ["title", "author"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_book_title_author", "books", type_="unique")
    # ### end Alembic commands ###
